# Generated by Django 3.1 on 2020-08-10 18:01

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('max_attendees', models.PositiveSmallIntegerField(default=5)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='guides.tourguideprofile')),
                ('languages', models.ManyToManyField(related_name='tours', to='utils.Language')),
                ('meeting_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.address')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.tourtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MaxValueValidator(Decimal('1000')), django.core.validators.MinValueValidator(Decimal('0'))])),
                ('details', models.TextField(blank=True, max_length=1024, null=True)),
                ('paid', models.DateTimeField(blank=True, null=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_tours', to='guides.tourguideprofile')),
                ('meeting_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.address')),
                ('purchaser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_booked_tours', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='personal_tours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.DateTimeField(blank=True, null=True)),
                ('refunded', models.DateTimeField(blank=True, null=True)),
                ('kicked_off', models.DateTimeField(blank=True, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='tours.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
