# Generated by Django 3.1 on 2020-08-10 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_attendee_personaltour_tour'),
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalguiderequest',
            name='tour',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.personaltour'),
        ),
        migrations.AddField(
            model_name='tourguiderating',
            name='personal_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='tours.personaltour'),
        ),
        migrations.AddField(
            model_name='tourguiderating',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='tours.tour'),
        ),
    ]
