# Generated by Django 3.1 on 2020-08-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_auto_20200810_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguideprofile',
            name='approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
