# Generated by Django 3.1 on 2020-08-14 11:44

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_auto_20200814_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalguiderequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalguiderequest',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
